/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adressenverwaltung.view;

/**
 *
 * @author marco
 */
public class AdressenverwaltungView extends javax.swing.JFrame
{

  /**
   * @param lblStatus the lblStatus to set
   */
  public void setLblStatus(javax.swing.JLabel lblStatus)
  {
    this.lblStatus = lblStatus;
  }

  /**
   * Creates new form adressenverwaltungView
   */
  public AdressenverwaltungView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    pmFile = new javax.swing.JPopupMenu();
    pmSave = new javax.swing.JMenuItem();
    pmOpen = new javax.swing.JMenuItem();
    pmUndo = new javax.swing.JMenuItem();
    pmDelete = new javax.swing.JMenuItem();
    pmAdd = new javax.swing.JMenuItem();
    fcDatei = new javax.swing.JFileChooser();
    iconToolbar = new javax.swing.JToolBar();
    btnOpen = new javax.swing.JButton();
    btnSave = new javax.swing.JButton();
    btnUndo = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();
    lblStatus = new javax.swing.JLabel();
    tbleScroller = new javax.swing.JScrollPane();
    tbleAdressenverwaltung = new javax.swing.JTable();
    mnuBar = new javax.swing.JMenuBar();
    mnuFile = new javax.swing.JMenu();
    mnuOpen = new javax.swing.JMenuItem();
    mnuSave = new javax.swing.JMenuItem();
    mnuUndo = new javax.swing.JMenuItem();
    mnuDelete = new javax.swing.JMenuItem();
    mnuAdd = new javax.swing.JMenuItem();
    mnuEdit = new javax.swing.JMenu();

    pmSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    pmSave.setText("Save");
    pmSave.setToolTipText("");
    pmSave.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pmSaveActionPerformed(evt);
      }
    });
    pmFile.add(pmSave);

    pmOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    pmOpen.setText("Open");
    pmFile.add(pmOpen);

    pmUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    pmUndo.setText("Undo");
    pmUndo.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pmUndoActionPerformed(evt);
      }
    });
    pmFile.add(pmUndo);

    pmDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
    pmDelete.setText("Delete");
    pmFile.add(pmDelete);

    pmAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PLUS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    pmAdd.setText("AddColumn");
    pmFile.add(pmAdd);

    fcDatei.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        fcDateiActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    iconToolbar.setRollover(true);

    btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Open24.gif"))); // NOI18N
    btnOpen.setToolTipText("Open");
    btnOpen.setFocusable(false);
    btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnOpen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnOpenActionPerformed(evt);
      }
    });
    iconToolbar.add(btnOpen);

    btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Save24.gif"))); // NOI18N
    btnSave.setToolTipText("Save");
    btnSave.setFocusable(false);
    btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    iconToolbar.add(btnSave);

    btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Undo24.gif"))); // NOI18N
    btnUndo.setToolTipText("Undo");
    btnUndo.setFocusable(false);
    btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    iconToolbar.add(btnUndo);

    btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Delete24.gif"))); // NOI18N
    btnDelete.setToolTipText("Delete");
    btnDelete.setFocusable(false);
    btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    iconToolbar.add(btnDelete);

    btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Add24.gif"))); // NOI18N
    btnAdd.setToolTipText("Add Column");
    btnAdd.setFocusable(false);
    btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    iconToolbar.add(btnAdd);

    getContentPane().add(iconToolbar, java.awt.BorderLayout.PAGE_START);

    lblStatus.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
    lblStatus.setText("File:");
    getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

    tbleAdressenverwaltung.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String []
      {
        "Name", "Telefon"
      }
    ));
    tbleAdressenverwaltung.setComponentPopupMenu(pmFile);
    tbleScroller.setViewportView(tbleAdressenverwaltung);
    tbleAdressenverwaltung.getAccessibleContext().setAccessibleName("");

    getContentPane().add(tbleScroller, java.awt.BorderLayout.CENTER);

    mnuFile.setMnemonic('F');
    mnuFile.setText("File");

    mnuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    mnuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Open24.gif"))); // NOI18N
    mnuOpen.setText("Open");
    mnuOpen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        mnuOpenActionPerformed(evt);
      }
    });
    mnuFile.add(mnuOpen);

    mnuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    mnuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Save24.gif"))); // NOI18N
    mnuSave.setText("Save");
    mnuSave.setToolTipText("");
    mnuFile.add(mnuSave);

    mnuUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    mnuUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Undo24.gif"))); // NOI18N
    mnuUndo.setText("Undo");
    mnuFile.add(mnuUndo);

    mnuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
    mnuDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Delete24.gif"))); // NOI18N
    mnuDelete.setText("Delete");
    mnuFile.add(mnuDelete);

    mnuAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PLUS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    mnuAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressenverwaltung/view/icons/Add24.gif"))); // NOI18N
    mnuAdd.setText("Add Column");
    mnuFile.add(mnuAdd);

    mnuBar.add(mnuFile);

    mnuEdit.setMnemonic('E');
    mnuEdit.setText("Edit");
    mnuBar.add(mnuEdit);

    setJMenuBar(mnuBar);

    setSize(new java.awt.Dimension(920, 469));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuOpenActionPerformed
  {//GEN-HEADEREND:event_mnuOpenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mnuOpenActionPerformed

  private void fcDateiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fcDateiActionPerformed
  {//GEN-HEADEREND:event_fcDateiActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fcDateiActionPerformed

  private void btnOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenActionPerformed
  {//GEN-HEADEREND:event_btnOpenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnOpenActionPerformed

  private void pmSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pmSaveActionPerformed
  {//GEN-HEADEREND:event_pmSaveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pmSaveActionPerformed

  private void pmUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pmUndoActionPerformed
  {//GEN-HEADEREND:event_pmUndoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pmUndoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(AdressenverwaltungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(AdressenverwaltungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(AdressenverwaltungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(AdressenverwaltungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new AdressenverwaltungView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnOpen;
  private javax.swing.JButton btnSave;
  private javax.swing.JButton btnUndo;
  private javax.swing.JFileChooser fcDatei;
  private javax.swing.JToolBar iconToolbar;
  private javax.swing.JLabel lblStatus;
  private javax.swing.JMenuItem mnuAdd;
  private javax.swing.JMenuBar mnuBar;
  private javax.swing.JMenuItem mnuDelete;
  private javax.swing.JMenu mnuEdit;
  private javax.swing.JMenu mnuFile;
  private javax.swing.JMenuItem mnuOpen;
  private javax.swing.JMenuItem mnuSave;
  private javax.swing.JMenuItem mnuUndo;
  private javax.swing.JMenuItem pmAdd;
  private javax.swing.JMenuItem pmDelete;
  private javax.swing.JPopupMenu pmFile;
  private javax.swing.JMenuItem pmOpen;
  private javax.swing.JMenuItem pmSave;
  private javax.swing.JMenuItem pmUndo;
  private javax.swing.JTable tbleAdressenverwaltung;
  private javax.swing.JScrollPane tbleScroller;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the btnOpen
   */
  public javax.swing.JButton getBtnOpen()
  {
    return btnOpen;
  }

  /**
   * @return the btnSave
   */
  public javax.swing.JButton getBtnSave()
  {
    return btnSave;
  }

  /**
   * @return the jFileChooser1
   */
  public javax.swing.JFileChooser getjFileChooser1()
  {
    return fcDatei;
  }

  /**
   * @return the fcDatei
   */
  public javax.swing.JFileChooser getFcDatei()
  {
    return fcDatei;
  }

  /**
   * @return the mnuOpen
   */
  public javax.swing.JMenuItem getMnuOpen()
  {
    return mnuOpen;
  }

  /**
   * @return the mnuSave
   */
  public javax.swing.JMenuItem getMnuSave()
  {
    return mnuSave;
  }

  

  /**
   * @return the lblStatus
   */
  public javax.swing.JLabel getLblStatus()
  {
    return lblStatus;
  }

  /**
   * @return the tbleAdressenverwaltung
   */
  public javax.swing.JTable getTbleAdressenverwaltung()
  {
    return tbleAdressenverwaltung;
  }

  /**
   * @param tbleAdressenverwaltung the tbleAdressenverwaltung to set
   */
  public void setTbleAdressenverwaltung(javax.swing.JTable tbleAdressenverwaltung)
  {
    this.tbleAdressenverwaltung = tbleAdressenverwaltung;
  }

  /**
   * @return the tbleScroller
   */
  public javax.swing.JScrollPane getTbleScroller()
  {
    return tbleScroller;
  }

  /**
   * @param tbleScroller the tbleScroller to set
   */
  public void setTbleScroller(javax.swing.JScrollPane tbleScroller)
  {
    this.tbleScroller = tbleScroller;
  }

  /**
   * @return the pmOpen
   */
  public javax.swing.JMenuItem getPmOpen()
  {
    return pmOpen;
  }

  /**
   * @return the pmSave
   */
  public javax.swing.JMenuItem getPmSave()
  {
    return pmSave;
  }

  /**
   * @return the btnUndo
   */
  public javax.swing.JButton getBtnUndo()
  {
    return btnUndo;
  }

  /**
   * @return the mnuUndo
   */
  public javax.swing.JMenuItem getMnuUndo()
  {
    return mnuUndo;
  }

  /**
   * @return the pmUndo
   */
  public javax.swing.JMenuItem getPmUndo()
  {
    return pmUndo;
  }

  /**
   * @return the btnDelete
   */
  public javax.swing.JButton getBtnDelete()
  {
    return btnDelete;
  }

  /**
   * @return the mnuDelete
   */
  public javax.swing.JMenuItem getMnuDelete()
  {
    return mnuDelete;
  }

  /**
   * @return the pmDelete
   */
  public javax.swing.JMenuItem getPmDelete()
  {
    return pmDelete;
  }

  /**
   * @return the btnAdd
   */
  public javax.swing.JButton getBtnAdd()
  {
    return btnAdd;
  }

  /**
   * @return the mnuAdd
   */
  public javax.swing.JMenuItem getMnuAdd()
  {
    return mnuAdd;
  }

  /**
   * @return the pmAdd
   */
  public javax.swing.JMenuItem getPmAdd()
  {
    return pmAdd;
  }
}
